--Автор добавил 1 файл со всеми стрингсами
--stringslocalization.lua

if STRINGS.TOO_MANY_ITEMS == nil then
	STRINGS.TOO_MANY_ITEMS = {
		UI = {
			BUTTON = {},
			DEBUG = {
				SEASON = {},
				TIME = {},
				SPEED = {},
				WEATHER = {},
				CHARACTER = {},
				SERVER = {},
			},
			SIDEBAR = {},
			SEARCHBAR = {},
			SEARCH = {},
		},
	}
end

STRINGS.TOO_MANY_ITEMS.UI.BUTTON.HEALTH = "Здоровье 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.SANITY = "Рассудок 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.HUNGER = "Голод 100%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.WET = "Влажность 0%"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.TEMPERATURE = "Температура: 20\176C"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.LOGMETER = "Древесный голод 100%"

STRINGS.TOO_MANY_ITEMS.UI.BUTTON.GODMODE = "Режим бога (Вкл/Выкл)"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.CREATIVEMODE = "Творческий режим  (Вкл/Выкл)"
STRINGS.TOO_MANY_ITEMS.UI.BUTTON.DEBUGMENU = "Меню отладки (Открыть/Закрыть)"



STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.SPRINGTIP = "Наступает весна!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.SUMMERTIP = "Наступает лето!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.AUTUMNTIP = "Наступает осень!"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SEASON.WINTERTIP = "Наступает зима!"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TEXT = "Время:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.NEXT = "Далее"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.NEXTTIP = "Следующая фаза дня"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.ODAY = "1 день"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.ODAYTIP = "Пропустить 1 день"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.FDAYS = "5 дней"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.FDAYSTIP = "Пропустить 5 дней"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TDAYS = "10 дней"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.TIME.TDAYSTIP = "Пропустить 10 дней"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.TEXT = "Скорость:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.SLOW = "Замедлить"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.SLOWTIP = "60% скорости"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.NORMAL = "Норма"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.NORMALTIP = "100% скорости"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FAST = "Ускорить"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FASTTIP = "200% скорости"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FLY = "Нитро"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SPEED.FLYTIP = "400% скорости"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.TEXT = "Погода:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.LIGHTNINGTIP = "Удар молнии"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.WATER = ".,;:':;,."
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.WATERTIP = "Дождь/Снег"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.NOWATER = ",.'o'.,"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.WEATHER.NOWATERTIP = "Остановить Дождь/Снег"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.TEXT = "Персонаж:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.KILL = "Убить"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.KILLTIP = "Убивает персонажа"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTERREBIRTH = "Возр."
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.REBIRTHTIP = "Возрождает персонажа"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.DESPAWN = "Смена"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.DESPAWNTIP = "К меню выбора персонажа"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.GATHER = "Собрать"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.GATHERTIP = "Собирает всех персонажей"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.UNLOCKTECH = "Крафт"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.CHARACTER.UNLOCKTECHTIP = "Разблокировать все предметы для меню крафта"


STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.TEXT = "Сервер:"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.RESET = "Рестарт"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.RESETTIP = "Рестарт текущей игры"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.REGENERATE = "Сброс"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.REGENERATETIP = "Создает новый мир"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.ROLLBACK = "Откат"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.ROLLBACKTIP = "Откат до последней сохраненной игры"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SAVE = "Сохр."
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SAVETIP = "Сохранить мир"
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SHUTDOWN = "Выкл."
STRINGS.TOO_MANY_ITEMS.UI.DEBUG.SERVER.SHUTDOWNTIP = "Выключить сервер"


STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.A = "В"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPA = "Все предметы"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.F = "Е"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPF = "Еда"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.R = "Р"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPR = "Ресурсы"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.W = "Б"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPW = "Бой"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.T = "И"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPT = "Инструменты"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.C = "О"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPC= "Одежда"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.G = "П"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPG= "Подарки"

STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.O = "Д"
STRINGS.TOO_MANY_ITEMS.UI.SIDEBAR.TIPO = "Другое (Бывают вылеты)"


STRINGS.TOO_MANY_ITEMS.UI.SEARCHBAR.TEXT = "Найти предмет!"
STRINGS.TOO_MANY_ITEMS.UI.SEARCHBAR.TIP = "Нажми!"
STRINGS.TOO_MANY_ITEMS.UI.SEARCH.TEXT= "Поиск"
STRINGS.TOO_MANY_ITEMS.UI.SEARCH.TIP = "Нажми для поиска!"

---------------------------всё