--Подмена названий режимов игры/описаний
local titlefix = {}

--Название режимов игры
titlefix["Relaxed"] = "Расслабленный"
titlefix["Endless"] = "Бесконечный"
titlefix["Survival"] = "Выживание"
titlefix["Forest Plus"] = "Стандарт+"
titlefix["Wilderness"] = "Свободный"
titlefix["Lights Out"] = "Без света"
titlefix["The Caves"] = "Пещеры"
titlefix["Caves Plus"] = "Пещеры+"
titlefix["Taste of Terraria"] = "Вкус Terraria"
titlefix["Caves of Terraria"] = "Пещеры Terraria"

--Описание режимов игры
titlefix["A more relaxed playstyle with less threats from the world.\nSurvivors will not die from starvation, freezing, overheating, or the darkness.\nDamage to survivors is reduced. Resurrection is always available via the Florid Postern."] = "Расслабляющий стиль игры с меньшим количеством угроз со стороны окружающего мира.\nВыживающие не умрут от голода, замерзания, перегрева или темноты.\nУрон по выживающим уменьшен. Воскрешение всегда доступно через вычурный потайной вход."
titlefix["A never-ending Don't Starve sandbox.\nResurrection is always available via the Florid Postern."] = "Бесконечная песочница \"Don't Starve\".\nВоскрешение всегда доступно через вычурный потайной вход."
titlefix["A quicker start in a harsher world."] = "Быстрый старт в более жёстком мире."
titlefix["The standard Don't Starve experience."] = "Стандартный шаблон Don't Starve."
titlefix["It's wild and dangerous out there!\nEnter at a random location in the world.\nWhen you die: pick a new survivor and try, try again."] = "Там дико и опасно!\nНачните со случайного места в мире.\nКогда умрёшь, выбери нового выживающего и пробуй снова и снова."
titlefix["A dark twist on the standard Don't Starve experience."] = "Тёмный вариант стандартного шаблона Don't Starve."
titlefix["Don't Starve Together, with a Terraria-inspired twist."] = "Don't Starve Together, с вдохновлённой Terraria изюминкой."
titlefix["Don't Starve Together, with a Terraria-inspired twist... in the caves!"] = "Don't Starve Together, с вдохновлённой Terraria изюминкой... в пещерах!"
titlefix["A darker, more arachnid-y cave experience."] = "Пещерный шаблон, в котором ещё темнее и паукастее."
titlefix["Delve into the caves... together!"] = "Спустимся в пещеры... вместе!"

--Радиобаттоны в настройках/найстроках генерации
titlefix["A Cold Reception"] = "Холодный приём"
titlefix["The King of Winter"] = "Король зимы"
titlefix["The Game is Afoot"] = "Игра началась"
titlefix["Archipelago"] = "Архипелаг"
titlefix["Two Worlds"] = "Два мира"
titlefix["Darkness"] = "Тьма"
titlefix["Checkmate"] = "Шах и Мат"
titlefix["Always"] = "Всегда"
titlefix["Autumn"] = "Осень"
titlefix["Autumn or Spring"] = "Осень или Весна"
titlefix["Default"] = "Стандарт"
titlefix["Least"] = "Меньше"
titlefix["Most"] = "Больше"
titlefix["Never"] = "Никогда"
titlefix["Caves"] = "Пещеры"
titlefix["Animals"] = "Животные"
titlefix["Events"] = "События"
titlefix["Food"] = "Еда"
titlefix["Giants"] = "Гиганты"
titlefix["Global"] = "Основное"
titlefix["World"] = "Мир"
titlefix["Monsters"] = "Монстры"
titlefix["Ocean"] = "Океан"
titlefix["Resources"] = "Ресурсы"
titlefix["Survivors"] = "Выживающие"
titlefix["Classic"] = "Классика"
titlefix["Dark"] = "Темно"
titlefix["Autumn"] = "Осень или весна"
titlefix["Default"] = "По умолчанию"
titlefix["Always"] = "Всегда"
titlefix["Auto Detect"] = "Авто"
titlefix["Never"] = "Никогда"
titlefix["Disabled"] = "Отключено"
titlefix["Dusk"] = "Вечер"
titlefix["Not Easy"] = "Не легко"
titlefix["Enabled"] = "Включено"
titlefix["Everything"] = "Всё"
titlefix["No"] = "Нет"
titlefix["OK"] = "ОК"
titlefix["Overly Taxing"] = "Сложно"
titlefix["Highly Random"] = "Крайне случайно"
titlefix["Instant"] = "Моментальный"
titlefix["Cave"] = "Пещера"
titlefix["Forest"] = "Лес"
titlefix["The Forge"] = "Кузня"
titlefix["The Gorge"] = "Ущелье"
titlefix["Caves"] = "Пещеры"
titlefix["Forest"] = "Лес"
titlefix["Always"] = "Всегда"
titlefix["Never"] = "Никогда"
titlefix["Default"] = "Стандарт"
titlefix["Cancel"] = "Отменить"
titlefix["Night"] = "Ночь"
titlefix["No"] = "Нет"
titlefix["None"] = "Нет"
titlefix["None Available"] = "Невозможно"
titlefix["Nonlethal"] = "Несмертельный"
titlefix["Plus"] = "Плюс"
titlefix["Florid Postern"] = "Вычурный потайной вход"
titlefix["Default"] = "По умолчанию"
titlefix["Big"] = "Большой"
titlefix["All"] = "Все"
titlefix["Few"] = "Немного"
titlefix["Many"] = "Много"
titlefix["Maximum"] = "Максимально"
titlefix["Medium"] = "Средне"
titlefix["None"] = "Нет"
titlefix["Normal"] = "Нормально"
titlefix["Random"] = "Случайно"
titlefix["Only"] = "Только"

titlefix["Long Day"] = "Длинный день"
titlefix["Long Dusk"] = "Длинный вечер"
titlefix["Long Night"] = "Длинная ночь"

titlefix["No Day"] = "Без дня"
titlefix["No Dusk"] = "Без вечера"
titlefix["No Night"] = "Без ночи"

titlefix["Only Day"] = "Только день"
titlefix["Only Dusk"] = "Только вечер"
titlefix["Only Night"] = "Только ночь"

titlefix["Change Survivor"] = "Поменять выжившего"
titlefix["Become a Ghost"] = "Стать призраком"

titlefix["After Day 10"] = "После 10-го дня"
titlefix["After Day 15"] = "После 15-го дня"
titlefix["After Day 20"] = "После 20-го дня"
titlefix["After Day 5"] = "После 5-го дня"

titlefix["Tons"] = "Много"
titlefix["Complex"] = "Сложный"
titlefix["Default"] = "Стандарт"
titlefix["Fast"] = "Быстро"
titlefix["Insane"] = "Безумно"
titlefix["Long"] = "Долго"
titlefix["Lots"] = "Много"
titlefix["None"] = "Нет"
titlefix["More"] = "Больше"
titlefix["Little"] = "Мало"
titlefix["Short"] = "Коротко"
titlefix["Huge"] = "Огромный"
titlefix["Simple"] = "Простой"
titlefix["Large"] = "Большой"
titlefix["Slow"] = "Медленно"
titlefix["Small"] = "Маленький"
titlefix["Medium"] = "Средний"
titlefix["Tiny"] = "Крошечный"
titlefix["Less"] = "Меньше"
titlefix["Very Complex"] = "Очень сложный"
titlefix["Very Fast"] = "Очень быстро"
titlefix["Very Long"] = "Очень долго"
titlefix["Very Short"] = "Очень коротко"
titlefix["Very Simple"] = "Очень простой"
titlefix["Very Slow"] = "Очень медленно"
titlefix["Midsummer Cawnival"] = "Карнавал летнего солнцестояния"
titlefix["Auto"] = "Авто"
titlefix["Hallowed Nights"] = "Хеллоуинские ночи"
titlefix["Winter's Feast"] = "Зимний банкет"
titlefix["Year of the Beefalo"] = "Год бифало"
titlefix["Year of the Carrat"] = "Год морквокрысы"
titlefix["Year of the Gobbler"] = "Год индюка"
titlefix["Year of the Pig King"] = "Год Короля свиней"
titlefix["Year of the Varg"] = "Год Варга"
titlefix["Year of the Catcoon"] = "Год енотокота"
titlefix["Spring"] = "Весна"
titlefix["Summer"] = "Лето"
titlefix["Winter"] = "Зима"
titlefix["Winter or Summer"] = "Зима или Лето"
titlefix["Creatures and Spawners"] = "Существа и откуда они появляются"
titlefix["Hostile Creatures and Spawners"] = "Враждебные существа и откуда они появляются"
titlefix["Creatures"] = "Существа"
titlefix["Hostile Creatures"] = "Враждебные существа"
titlefix["Unnatural Portal Resources"] = "Ресурсы неестественного портала"
titlefix["Resource Regrowth"] = "Возобновление ресурсов"
titlefix["Yes"] = "Да"

local oldSetString = _G.TextWidget.SetString
_G.TextWidget.SetString = function(guid, str)
	if type(str)=="string" then
		str = titlefix[str] or str
	end
	oldSetString(guid, str)
end